model: "QuartzNet"
sample_rate: 16000
repeat:  &rep  3
dropout: &drop 0.1

AudioToTextDataLayer:
    max_duration: 16.7
    trim_silence: true

    train:
        shuffle: true

    eval:
        shuffle: false
        max_duration: null

AudioPreprocessing:
    window_size: 0.02
    window_stride: 0.01
    window: "hann"
    normalize: "per_feature"
    n_fft: 512
    features: 40
    feat_type: "logfbank"
    dither: 0.00001
    pad_to: 16
    stft_conv: true

SpectrogramAugmentation:
    rect_masks: 5
    rect_time: 120
    rect_freq: 50

JasperEncoder:
    activation: "relu"
    conv_mask: true
#    normalization_mode: "batch"

    jasper:
      - filters: 256
        repeat: 1
        kernel: [15]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: false
        separable: true

      - filters: 256
        repeat: *rep
        kernel: [21]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 256
        repeat: *rep
        kernel: [25]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 256
        repeat: *rep
        kernel: [29]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 256
        repeat: *rep
        kernel: [33]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 256
        repeat: *rep
        kernel: [37]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 256
        repeat: *rep
        kernel: [41]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 512
        repeat: *rep
        kernel: [45]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 512
        repeat: *rep
        kernel: [49]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 512
        repeat: *rep
        kernel: [51]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 512
        repeat: *rep
        kernel: [55]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 512
        repeat: *rep
        kernel: [59]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 512
        repeat: *rep
        kernel: [63]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 512
        repeat: *rep
        kernel: [67]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 512
        repeat: *rep
        kernel: [71]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 512
        repeat: *rep
        kernel: [75]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: true
        separable: true

      - filters: 512
        repeat: 1
        kernel: [87]
        stride: [1]
        dilation: [2]
        dropout: *drop
        residual: false
        separable: true

      - filters: 1024
        repeat: 1
        kernel: [1]
        stride: [1]
        dilation: [1]
        dropout: *drop
        residual: false

labels: [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
         "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"]
